# pylint: skip-file
# Generated by Django 2.2.9 on 2020-03-18 11:34
from django.db import migrations
from onadata.libs.utils.common_tools import get_uuid


def generate_uuid_if_missing(apps, schema_editor):
    """
    Generate uuids for XForms without them
    """
    XForm = apps.get_model('logger', 'XForm')

    for form in XForm.objects.filter(uuid=''):
        form.uuid = get_uuid()
        form.save()


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0060_auto_20200305_0357'),
    ]

    operations = [
        migrations.RunPython(generate_uuid_if_missing)]
